server:
  port: 8081

#db configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/blogapp_backendapis
    username: shiva
    password: shiva*

  #jpa configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

    #hibernate configuration
    hibernate:
#      create, update, create-update, validate
      ddl-auto: update

    show-sql: true

#  file upload settings
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


#jwt:
#  secret: